services:
  web:
    image: nginx
    build:
      context: ./nginx
    ports:
      -  "8889:443"
    #command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - transcendence_nginx_network

  game-back:
    container_name: game-back
    build:
      context: ./game/back
    networks:
      - transcendence_nginx_network
    environment:
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    networks:
      - transcendence_nginx_network

  # start of auth containers
  # ==========================================================================
  # CONTAINER 1: DATABASE (PostgreSQL)
  # ==========================================================================
  db:
    image: postgres:16-alpine
    container_name: transcendence_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================================================
  # CONTAINER 2: BACKEND (Fastify + Prisma + TypeScript)
  # ==========================================================================
  backend:
    build:
      context: ./users/
      dockerfile: Dockerfile
    container_name: transcendence_backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      FORTY_TWO_CLIENT_ID: ${FORTY_TWO_CLIENT_ID}
      FORTY_TWO_CLIENT_SECRET: ${FORTY_TWO_CLIENT_SECRET}
      FORTY_TWO_REDIRECT_URI: ${FORTY_TWO_REDIRECT_URI}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      # Only persist avatars and prisma, do not overwrite dist/
      - avatars_data:/app/public/avatars

    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence_network
      - transcendence_nginx_network
  # ==========================================================================
  # CONTAINER 3: SOCIAL CHAT (Express + Prisma + TypeScript)
  # ==========================================================================
  social-chat-back:
    container_name: social-chat-back
    build:
      context: ./social-chat/back
    environment:
      PORT: 8890
      DATABASE_URL: ${CHAT_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      USERS_INTERNAL_URL: http://backend:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transcendence_network
      - transcendence_nginx_network

networks:
  game_network:
    name: game_network
  auth_network:
    name: auth_network
  transcendence_network:
    name: transcendence_network
  transcendence_nginx_network:
    name: transcendence_nginx_network

volumes:
  postgres_data:
    driver: local
  avatars_data:
      driver: local