events {}

http {
    resolver 127.0.0.11 valid=10s;

    server {
        listen              443 ssl;
        server_name         transcendence.42.fr;
        ssl_certificate     /etc/nginx/ssl/transcendence.42.fr.crt;
        ssl_certificate_key /etc/nginx/ssl/transcendence.42.fr.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location /api/auth/ {
            set $users backend;
            rewrite ^/api/auth/(.*)$ /$1 break;
            proxy_pass http://$users:3000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 2s;
            proxy_read_timeout 10s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }

        location /api/game/ {
            set $game game-back;
            rewrite ^/api/game/(.*)$ /$1 break;
            proxy_pass http://$game:8888;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 1h;
            proxy_send_timeout 1h;

            proxy_connect_timeout 2s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }
         location /api/chat/ws {
            proxy_pass http://social-chat-back:8890/chat/ws;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /api/chat/ {
            set $chat social-chat-back;
            rewrite ^/api/chat/(.*)$ /chat/$1 break;
            proxy_pass http://$chat:8890;

            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        location / {
            proxy_pass http://frontend:3000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 2s;
            proxy_read_timeout 10s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }
    }
}