// ┌────────────────────────────────────────────────────────────┐
// │                   LightingConfig.ts                        │
// ├────────────────────────────────────────────────────────────┤
// │ Defines lighting settings for the 3D Hub scene.            │
// │ Controls ambient light, main light and shadow quality.     │
// │ It does NOT create lights or apply shadows directly.       │
// └────────────────────────────────────────────────────────────┘
// STEP 1: Define all lighting values used by the 3D Hub setup.
// These values are consumed later by the lighting setup system.
export const LIGHTING_CONFIG = {
	// STEP 2: Define ambient light settings.
	// Ambient light prevents the scene from becoming completely dark.
	ambientLight: {
		intensity: 0.5,
		groundColor: [0.9, 0.9, 0.9] as [number, number, number], 
	},
	// STEP 3: Define the main directional light settings.
	// This behaves like the primary sun-style light of the Hub.
	mainLight: {
		direction: [-1, -2, -1] as [number, number, number], 
		position: [20, 40, 20] as [number, number, number],
		intensity: 0.9, 
	},
	// STEP 4: Define shadow rendering settings.
	// These values balance visual quality and performance.
	shadows: {
		resolution: 512,
		softness: 16,
		darkness: 0.4, 
	},

} as const;
// STEP 5: Small terminology notes.
// ambientLight: global fill light used to avoid fully black areas.
// mainLight: primary directional light, similar to sunlight.
// direction: vector that defines where the light points.
// position: world position where the light is placed.
// shadows: dark projected areas generated by objects blocking light.
// resolution: quality of the shadow map.
// softness: blur/smoothness of the shadow edges.
// darkness: intensity of the shadow.
// intensity: strength of the light.